var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/auth/logout/route.js")
R.c("server/chunks/[root-of-the-server]__6e079cc5._.js")
R.c("server/chunks/src_backend_utils_jwt_ts_a8a7fceb._.js")
R.c("server/chunks/src_backend_controllers_auth_controller_ts_900e9af6._.js")
R.c("server/chunks/[root-of-the-server]__4ce7d628._.js")
R.c("server/chunks/[root-of-the-server]__aad3751c._.js")
R.c("server/chunks/node_modules_next_48b9435f._.js")
R.m(79543)
R.m(83932)
module.exports=R.m(83932).exports
