module.exports=[11949,e=>{"use strict";e.s(["baseURL",()=>r],11949);let i={src:e.i(54377).default,width:273,height:78,blurWidth:0,blurHeight:0},t=(e.i(54349).default,e.i(61108).default,e.i(49529).default,e.i(32206).default,e.i(73583).default,e.i(82922).default,e.i(68161).default,e.i(88151).default,e.i(34542).default,e.i(68718).default,e.i(34611).default,e.i(70622).default,e.i(88647).default,e.i(94832).default,e.i(83621).default,e.i(29572).default,e.i(5657).default,e.i(5631).default,e.i(84354).default,e.i(3828).default,e.i(27051).default,e.i(75689).default,e.i(30952).default,e.i(31442).default,e.i(23798).default,e.i(12060).default,e.i(19916).default,e.i(98652).default,e.i(86370).default,e.i(31750).default,e.i(79464).default,{logo:i});var o=e.i(75949);let r="https://www.averis.co.uk";t.logo.src,t.logo.src,o.COMPANY_EMAIL,o.COMPANY_PHONE,o.COMPANY_ADDRESS,o.COMPANY_LEGAL_NAME,o.COMPANY_NUMBER,o.COMPANY_ADDRESS,o.COMPANY_EMAIL,o.COMPANY_PHONE},70943,(e,i,t)=>{"use strict";function o(e){return Array.isArray(e)?e:[e]}function r(e){if(null!=e)return o(e)}function l(e){let i;if("string"==typeof e)try{i=(e=new URL(e)).origin}catch{}return i}Object.defineProperty(t,"__esModule",{value:!0}),!function(e,i){for(var t in i)Object.defineProperty(e,t,{enumerable:!0,get:i[t]})}(t,{getOrigin:function(){return l},resolveArray:function(){return o},resolveAsArrayOrUndefined:function(){return r}})},82930,(e,i,t)=>{"use strict";Object.defineProperty(t,"__esModule",{value:!0}),!function(e,i){for(var t in i)Object.defineProperty(e,t,{enumerable:!0,get:i[t]})}(t,{resolveManifest:function(){return n},resolveRobots:function(){return r},resolveRouteData:function(){return a},resolveSitemap:function(){return l}});let o=e.r(70943);function r(e){let i="";for(let t of Array.isArray(e.rules)?e.rules:[e.rules]){for(let e of(0,o.resolveArray)(t.userAgent||["*"]))i+=`User-Agent: ${e}
`;if(t.allow)for(let e of(0,o.resolveArray)(t.allow))i+=`Allow: ${e}
`;if(t.disallow)for(let e of(0,o.resolveArray)(t.disallow))i+=`Disallow: ${e}
`;t.crawlDelay&&(i+=`Crawl-delay: ${t.crawlDelay}
`),i+="\n"}return e.host&&(i+=`Host: ${e.host}
`),e.sitemap&&(0,o.resolveArray)(e.sitemap).forEach(e=>{i+=`Sitemap: ${e}
`}),i}function l(e){let i=e.some(e=>Object.keys(e.alternates??{}).length>0),t=e.some(e=>{var i;return!!(null==(i=e.images)?void 0:i.length)}),o=e.some(e=>{var i;return!!(null==(i=e.videos)?void 0:i.length)}),r="";for(let d of(r+='<?xml version="1.0" encoding="UTF-8"?>\n',r+='<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"',t&&(r+=' xmlns:image="http://www.google.com/schemas/sitemap-image/1.1"'),o&&(r+=' xmlns:video="http://www.google.com/schemas/sitemap-video/1.1"'),i?r+=' xmlns:xhtml="http://www.w3.org/1999/xhtml">\n':r+=">\n",e)){var l,n,a;r+="<url>\n",r+=`<loc>${d.url}</loc>
`;let e=null==(l=d.alternates)?void 0:l.languages;if(e&&Object.keys(e).length)for(let i in e)r+=`<xhtml:link rel="alternate" hreflang="${i}" href="${e[i]}" />
`;if(null==(n=d.images)?void 0:n.length)for(let e of d.images)r+=`<image:image>
<image:loc>${e}</image:loc>
</image:image>
`;if(null==(a=d.videos)?void 0:a.length)for(let e of d.videos)r+=["<video:video>",`<video:title>${e.title}</video:title>`,`<video:thumbnail_loc>${e.thumbnail_loc}</video:thumbnail_loc>`,`<video:description>${e.description}</video:description>`,e.content_loc&&`<video:content_loc>${e.content_loc}</video:content_loc>`,e.player_loc&&`<video:player_loc>${e.player_loc}</video:player_loc>`,e.duration&&`<video:duration>${e.duration}</video:duration>`,e.view_count&&`<video:view_count>${e.view_count}</video:view_count>`,e.tag&&`<video:tag>${e.tag}</video:tag>`,e.rating&&`<video:rating>${e.rating}</video:rating>`,e.expiration_date&&`<video:expiration_date>${e.expiration_date}</video:expiration_date>`,e.publication_date&&`<video:publication_date>${e.publication_date}</video:publication_date>`,e.family_friendly&&`<video:family_friendly>${e.family_friendly}</video:family_friendly>`,e.requires_subscription&&`<video:requires_subscription>${e.requires_subscription}</video:requires_subscription>`,e.live&&`<video:live>${e.live}</video:live>`,e.restriction&&`<video:restriction relationship="${e.restriction.relationship}">${e.restriction.content}</video:restriction>`,e.platform&&`<video:platform relationship="${e.platform.relationship}">${e.platform.content}</video:platform>`,e.uploader&&`<video:uploader${e.uploader.info&&` info="${e.uploader.info}"`}>${e.uploader.content}</video:uploader>`,`</video:video>
`].filter(Boolean).join("\n");if(d.lastModified){let e=d.lastModified instanceof Date?d.lastModified.toISOString():d.lastModified;r+=`<lastmod>${e}</lastmod>
`}d.changeFrequency&&(r+=`<changefreq>${d.changeFrequency}</changefreq>
`),"number"==typeof d.priority&&(r+=`<priority>${d.priority}</priority>
`),r+="</url>\n"}return r+"</urlset>\n"}function n(e){return JSON.stringify(e)}function a(e,i){return"robots"===i?r(e):"sitemap"===i?l(e):"manifest"===i?n(e):""}}];

//# sourceMappingURL=_c8d9a64c._.js.map