var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/profile/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__ce027668._.js")
R.c("server/chunks/ssr/node_modules_next_9a0f1e8e._.js")
R.c("server/chunks/ssr/node_modules_next_dist_db14db6f._.js")
R.c("server/chunks/ssr/src_app_ca777385._.js")
R.c("server/chunks/ssr/src_804d8a63._.js")
R.c("server/chunks/ssr/node_modules_next_bddb08f2._.js")
R.c("server/chunks/ssr/_5e4ee9d5._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_2fffaa3a._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/[root-of-the-server]__d60acd35._.js")
R.c("server/chunks/ssr/_e1903320._.js")
R.c("server/chunks/ssr/_aee5ea43._.js")
R.m(10519)
R.m(89311)
module.exports=R.m(89311).exports
