export interface CountryOption {
    code: string;
    label: string;
}

const EXCLUDED_COUNTRY_CODES = new Set([
    "RUS",
    "BLR",
    "IRN",
    "PRK",
    "SYR",
    "YEM",
    "AFG",
    "SDN",
    "SSD",
    "CUB",
    "VEN",
    "ZWE",
    "MMR",
    "MLI",
    "COD",
    "CAF",
    "SOM",
    "IRQ",
    "HTI",
]);

const ALL_COUNTRIES: CountryOption[] = [
    { code: "ALB", label: "Albania" },
    { code: "DZA", label: "Algeria" },
    { code: "AND", label: "Andorra" },
    { code: "AGO", label: "Angola" },
    { code: "ATG", label: "Antigua and Barbuda" },
    { code: "ARG", label: "Argentina" },
    { code: "ARM", label: "Armenia" },
    { code: "AUS", label: "Australia" },
    { code: "AUT", label: "Austria" },
    { code: "AZE", label: "Azerbaijan" },
    { code: "BHS", label: "Bahamas" },
    { code: "BHR", label: "Bahrain" },
    { code: "BGD", label: "Bangladesh" },
    { code: "BRB", label: "Barbados" },
    { code: "BEL", label: "Belgium" },
    { code: "BLZ", label: "Belize" },
    { code: "BEN", label: "Benin" },
    { code: "BTN", label: "Bhutan" },
    { code: "BOL", label: "Bolivia" },
    { code: "BIH", label: "Bosnia and Herzegovina" },
    { code: "BWA", label: "Botswana" },
    { code: "BRA", label: "Brazil" },
    { code: "BRN", label: "Brunei" },
    { code: "BGR", label: "Bulgaria" },
    { code: "BFA", label: "Burkina Faso" },
    { code: "BDI", label: "Burundi" },
    { code: "CPV", label: "Cabo Verde" },
    { code: "KHM", label: "Cambodia" },
    { code: "CMR", label: "Cameroon" },
    { code: "CAN", label: "Canada" },
    { code: "TCD", label: "Chad" },
    { code: "CHL", label: "Chile" },
    { code: "CHN", label: "China" },
    { code: "COL", label: "Colombia" },
    { code: "COM", label: "Comoros" },
    { code: "COG", label: "Congo" },
    { code: "CRI", label: "Costa Rica" },
    { code: "CIV", label: "Cote d'Ivoire" },
    { code: "HRV", label: "Croatia" },
    { code: "CYP", label: "Cyprus" },
    { code: "CZE", label: "Czech Republic" },
    { code: "DNK", label: "Denmark" },
    { code: "DJI", label: "Djibouti" },
    { code: "DMA", label: "Dominica" },
    { code: "DOM", label: "Dominican Republic" },
    { code: "ECU", label: "Ecuador" },
    { code: "EGY", label: "Egypt" },
    { code: "SLV", label: "El Salvador" },
    { code: "GNQ", label: "Equatorial Guinea" },
    { code: "ERI", label: "Eritrea" },
    { code: "EST", label: "Estonia" },
    { code: "SWZ", label: "Eswatini" },
    { code: "ETH", label: "Ethiopia" },
    { code: "FJI", label: "Fiji" },
    { code: "FIN", label: "Finland" },
    { code: "FRA", label: "France" },
    { code: "GAB", label: "Gabon" },
    { code: "GMB", label: "Gambia" },
    { code: "GEO", label: "Georgia" },
    { code: "DEU", label: "Germany" },
    { code: "GHA", label: "Ghana" },
    { code: "GRC", label: "Greece" },
    { code: "GRD", label: "Grenada" },
    { code: "GTM", label: "Guatemala" },
    { code: "GIN", label: "Guinea" },
    { code: "GNB", label: "Guinea-Bissau" },
    { code: "GUY", label: "Guyana" },
    { code: "HND", label: "Honduras" },
    { code: "HUN", label: "Hungary" },
    { code: "ISL", label: "Iceland" },
    { code: "IND", label: "India" },
    { code: "IDN", label: "Indonesia" },
    { code: "IRL", label: "Ireland" },
    { code: "ISR", label: "Israel" },
    { code: "ITA", label: "Italy" },
    { code: "JAM", label: "Jamaica" },
    { code: "JPN", label: "Japan" },
    { code: "JOR", label: "Jordan" },
    { code: "KAZ", label: "Kazakhstan" },
    { code: "KEN", label: "Kenya" },
    { code: "KIR", label: "Kiribati" },
    { code: "KWT", label: "Kuwait" },
    { code: "KGZ", label: "Kyrgyzstan" },
    { code: "LAO", label: "Laos" },
    { code: "LVA", label: "Latvia" },
    { code: "LBN", label: "Lebanon" },
    { code: "LSO", label: "Lesotho" },
    { code: "LBR", label: "Liberia" },
    { code: "LBY", label: "Libya" },
    { code: "LIE", label: "Liechtenstein" },
    { code: "LTU", label: "Lithuania" },
    { code: "LUX", label: "Luxembourg" },
    { code: "MDG", label: "Madagascar" },
    { code: "MWI", label: "Malawi" },
    { code: "MYS", label: "Malaysia" },
    { code: "MDV", label: "Maldives" },
    { code: "MLT", label: "Malta" },
    { code: "MHL", label: "Marshall Islands" },
    { code: "MRT", label: "Mauritania" },
    { code: "MUS", label: "Mauritius" },
    { code: "MEX", label: "Mexico" },
    { code: "FSM", label: "Micronesia" },
    { code: "MDA", label: "Moldova" },
    { code: "MCO", label: "Monaco" },
    { code: "MNG", label: "Mongolia" },
    { code: "MNE", label: "Montenegro" },
    { code: "MAR", label: "Morocco" },
    { code: "MOZ", label: "Mozambique" },
    { code: "NAM", label: "Namibia" },
    { code: "NRU", label: "Nauru" },
    { code: "NPL", label: "Nepal" },
    { code: "NLD", label: "Netherlands" },
    { code: "NZL", label: "New Zealand" },
    { code: "NIC", label: "Nicaragua" },
    { code: "NER", label: "Niger" },
    { code: "NGA", label: "Nigeria" },
    { code: "MKD", label: "North Macedonia" },
    { code: "NOR", label: "Norway" },
    { code: "OMN", label: "Oman" },
    { code: "PAK", label: "Pakistan" },
    { code: "PLW", label: "Palau" },
    { code: "PSE", label: "Palestine" },
    { code: "PAN", label: "Panama" },
    { code: "PNG", label: "Papua New Guinea" },
    { code: "PRY", label: "Paraguay" },
    { code: "PER", label: "Peru" },
    { code: "PHL", label: "Philippines" },
    { code: "POL", label: "Poland" },
    { code: "PRT", label: "Portugal" },
    { code: "QAT", label: "Qatar" },
    { code: "ROU", label: "Romania" },
    { code: "RWA", label: "Rwanda" },
    { code: "KNA", label: "Saint Kitts and Nevis" },
    { code: "LCA", label: "Saint Lucia" },
    { code: "VCT", label: "Saint Vincent and the Grenadines" },
    { code: "WSM", label: "Samoa" },
    { code: "SMR", label: "San Marino" },
    { code: "STP", label: "Sao Tome and Principe" },
    { code: "SAU", label: "Saudi Arabia" },
    { code: "SEN", label: "Senegal" },
    { code: "SRB", label: "Serbia" },
    { code: "SYC", label: "Seychelles" },
    { code: "SLE", label: "Sierra Leone" },
    { code: "SGP", label: "Singapore" },
    { code: "SVK", label: "Slovakia" },
    { code: "SVN", label: "Slovenia" },
    { code: "SLB", label: "Solomon Islands" },
    { code: "ZAF", label: "South Africa" },
    { code: "KOR", label: "South Korea" },
    { code: "ESP", label: "Spain" },
    { code: "LKA", label: "Sri Lanka" },
    { code: "SUR", label: "Suriname" },
    { code: "SWE", label: "Sweden" },
    { code: "CHE", label: "Switzerland" },
    { code: "TJK", label: "Tajikistan" },
    { code: "TZA", label: "Tanzania" },
    { code: "THA", label: "Thailand" },
    { code: "TLS", label: "Timor-Leste" },
    { code: "TGO", label: "Togo" },
    { code: "TON", label: "Tonga" },
    { code: "TTO", label: "Trinidad and Tobago" },
    { code: "TUN", label: "Tunisia" },
    { code: "TUR", label: "Turkey" },
    { code: "TKM", label: "Turkmenistan" },
    { code: "TUV", label: "Tuvalu" },
    { code: "UGA", label: "Uganda" },
    { code: "UKR", label: "Ukraine" },
    { code: "ARE", label: "United Arab Emirates" },
    { code: "GBR", label: "United Kingdom" },
    { code: "USA", label: "United States" },
    { code: "URY", label: "Uruguay" },
    { code: "UZB", label: "Uzbekistan" },
    { code: "VUT", label: "Vanuatu" },
    { code: "VAT", label: "Vatican City" },
    { code: "VNM", label: "Vietnam" },
    { code: "ZMB", label: "Zambia" },
];

export const ALLOWED_COUNTRIES = ALL_COUNTRIES.filter(
    (country) => !EXCLUDED_COUNTRY_CODES.has(country.code)
);

const ALLOWED_COUNTRY_LABEL_SET = new Set(ALLOWED_COUNTRIES.map((country) => country.label));

export function isAllowedCountry(country: string) {
    return ALLOWED_COUNTRY_LABEL_SET.has(country);
}
