var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/spoynt/create-invoice/route.js")
R.c("server/chunks/_4c9c6c94._.js")
R.c("server/chunks/node_modules_next_48b9435f._.js")
R.c("server/chunks/[root-of-the-server]__1d215c1a._.js")
R.c("server/chunks/[root-of-the-server]__4ce7d628._.js")
R.c("server/chunks/[root-of-the-server]__aad3751c._.js")
R.c("server/chunks/src_backend_utils_jwt_ts_a8a7fceb._.js")
R.m(6717)
R.m(61364)
module.exports=R.m(61364).exports
