// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/about-us" | "/contact-us" | "/cookie-policy" | "/dashboard" | "/faq" | "/get-started" | "/payment/error" | "/payment/success" | "/pricing" | "/privacy-policy" | "/profile" | "/refund-policy" | "/services" | "/sign-in" | "/sign-up" | "/templates" | "/terms-and-conditions"
type AppRouteHandlerRoutes = "/api/ai/create-order" | "/api/ai/get-all-orders" | "/api/ai/get-order" | "/api/auth/login" | "/api/auth/logout" | "/api/auth/me" | "/api/auth/refresh" | "/api/auth/register" | "/api/contact" | "/api/cv/create-order" | "/api/cv/get-all-orders" | "/api/cv/get-order" | "/api/og" | "/api/spoynt/confirm" | "/api/spoynt/create-invoice" | "/api/spoynt/status/[reference]" | "/api/spoynt/webhook" | "/api/transactions/get-all" | "/api/universal/create-order" | "/api/universal/get-order" | "/api/universal/get-orders" | "/api/upload" | "/api/user/buy-tokens"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/about-us": {}
  "/api/ai/create-order": {}
  "/api/ai/get-all-orders": {}
  "/api/ai/get-order": {}
  "/api/auth/login": {}
  "/api/auth/logout": {}
  "/api/auth/me": {}
  "/api/auth/refresh": {}
  "/api/auth/register": {}
  "/api/contact": {}
  "/api/cv/create-order": {}
  "/api/cv/get-all-orders": {}
  "/api/cv/get-order": {}
  "/api/og": {}
  "/api/spoynt/confirm": {}
  "/api/spoynt/create-invoice": {}
  "/api/spoynt/status/[reference]": { "reference": string; }
  "/api/spoynt/webhook": {}
  "/api/transactions/get-all": {}
  "/api/universal/create-order": {}
  "/api/universal/get-order": {}
  "/api/universal/get-orders": {}
  "/api/upload": {}
  "/api/user/buy-tokens": {}
  "/contact-us": {}
  "/cookie-policy": {}
  "/dashboard": {}
  "/faq": {}
  "/get-started": {}
  "/payment/error": {}
  "/payment/success": {}
  "/pricing": {}
  "/privacy-policy": {}
  "/profile": {}
  "/refund-policy": {}
  "/services": {}
  "/sign-in": {}
  "/sign-up": {}
  "/templates": {}
  "/terms-and-conditions": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
